#!/bin/bash

export mUID=`id -u`
#export mGID=`id -g`
#export mGID=`groups`

for gr in `id -G`; do
  [ "${gr}" -eq "0" ] && echo "skipping group ${gr}" && continue
  getent group ${gr} >/dev/null 2>&1
  if [ "$?" != "0" ]; then
    export mGID=$gr
    if ! grep ^ssh-group /etc/group >/dev/null 2>&1; then
      echo "ssh-group:x:${gr}:" >> /etc/group
    fi
  fi
done

if ! grep ^ssh-user /etc/passwd >/dev/null 2>&1; then
  sed -e "/^${mUID}:.*/d" /etc/passwd > /tmp/new_passwd
  cat /tmp/new_passwd > /etc/passwd
  rm -f /tmp/new_passwd
  echo "ssh-user:x:${mUID}:${mGID}::/var/www:/bin/bash" >> /etc/passwd
fi

[ -z $HOME ] && exit 0
if [ ! -f "${HOME}/.bashrc" ]; then
  cat << 'EOF' > ${HOME}/.bashrc
  export PATH="/usr/local/composer/vendor/bin:/usr/local/composer/vendor/drush/drush:$PATH"
  export PS1='\u:\w\$ '
  export TERM=xterm-256color
EOF
fi

