#!/bin/bash
set -e

export mUID=`id -u`
#export mGID=`id -g`
#export mGID=`groups`

for gr in `id -G`; do
  [ "$gr" == "0" ] && continue
  getent group $gr
  if [ "$?" != "0" ]; then
    echo "ssh-group:x:${gr}" >> /etc/group
    export mGID=$gr
  fi
done

echo "ssh-user:x:${mUID}:${mGID}::/var/www:/bin/bash" >> /etc/passwd
echo "ssh-user:x:${mGID}" >> /etc/group

[ -z $WORKDIR ] && exit 0
if [ ! -f "${WORKDIR}/.bashrc" ]; then
  cat << 'EOF' > ${WORKDIR}/.bashrc
  export PATH="/usr/local/composer/vendor/bin:/usr/local/composer/vendor/drush/drush:$PATH"
  export PS1='\u:\w\$ '
  export TERM=xterm-256color
EOF
fi
