#!/bin/bash
set -e

export PATH="/usr/local/composer/vendor/bin:/usr/local/composer/vendor/drush/drush:$PATH"
export mUID=`id -u`
export mGID=`id -g`
export LINE="ssh-user:x:$mUID:$mGID::/var/www/html:/bin/bash"
echo >>/etc/passwd $LINE
