#!/bin/bash

cat <<EOF >> /etc/bash.bashrc
export HOME=/var/www
export PYENV_ROOT="\${HOME}/.pyenv"
export PATH="\${PYENV_ROOT}/bin:\${PATH}"
export PATH="\${PYENV_ROOT}/shims:\${PATH}"
export PYENV_SHELL=bash
source "\${PYENV_ROOT}/libexec/../completions/pyenv.bash"
command pyenv rehash 2>/dev/null
pyenv() {
  local command
  command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi
  case "\$command" in
  rehash|shell)
    eval "\$(pyenv "sh-\$command" "\$@")";;
  *)
    command pyenv "\$command" "\$@";;
  esac
}
EOF
